### ISSUE TITLE
Fails to build on Arch Linux

### ISSUE THREAD

**Issue by spacepluk** [floooh/fips-hello-world#2]
Hi there, I'm giving fips a try and I started following the instructions in the documentation, but `./fips build` is giving me this:

```
$ ./fips build
=== dependency: 'fips-hello-dep1':
Cloning into 'fips-hello-dep1'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 53 (delta 14), reused 52 (delta 14), pack-reused 0
Unpacking objects: 100% (53/53), done.
=== dependency: 'fips-hello-dep2':
Cloning into 'fips-hello-dep2'...
remote: Counting objects: 62, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 62 (delta 17), reused 62 (delta 17), pack-reused 0
Unpacking objects: 100% (62/62), done.
=== dependency: 'fips-hello-dep3':
Cloning into 'fips-hello-dep3'...
remote: Counting objects: 85, done.
remote: Total 85 (delta 0), reused 0 (delta 0), pack-reused 85
Unpacking objects: 100% (85/85), done.
=== revision: '191f59f0':
Note: checking out '191f59f0'.

You are in 'detached HEAD' state. You can look around, make experimental                                              
changes and commit them, and you can discard any commits you make in this                                             
state without impacting any branches by performing another checkout.                                                  

If you want to create a new branch to retain commits you create, you may                                              
do so (now or later) by using -b with the checkout command again. Example:                                            

  git checkout -b <new-branch-name>

HEAD is now at 191f59f First commit - working version 1
Traceback (most recent call last):
  File "./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/home/spacepluk/hacking/fips/mod/fips.py", line 49, in run                                                    
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)                                                        
  File "/home/spacepluk/hacking/fips/verbs/build.py", line 19, in run                                                 
    project.build(fips_dir, proj_dir, cfg_name)
  File "/home/spacepluk/hacking/fips/mod/project.py", line 229, in build                                              
    dep.fetch_imports(fips_dir, proj_dir)
  File "/home/spacepluk/hacking/fips/mod/dep.py", line 228, in fetch_imports                                          
    _rec_fetch_imports(fips_dir, proj_dir, [])
  File "/home/spacepluk/hacking/fips/mod/dep.py", line 204, in _rec_fetch_imports                                     
    dep_ok = git.checkout(dep_proj_dir, git_commit)
  File "/home/spacepluk/hacking/fips/mod/tools/git.py", line 188, in checkout                                         
    return output.split(':')[0] != 'error'
TypeError: a bytes-like object is required, not 'str'
```

**Comment by floooh** [comment]
Argh, looks like a python3 issue specifically with checking out a 'version-tagged' dependency. For 'normal situations' it should work. I'm starting to work on a fix.

Thanks for the bug report!

**Comment by floooh** [comment]
I have opened a ticket in the fips projects and will close this ticket here.
